apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: themepark-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: themepark-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
